[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "HSMM"
version = "0.1.0"
requires-python = ">= 3.8"
dependencies = [
    "numpy",
    "scipy>=1.13",
    "scikit-learn"
]

[project.optional-dependencies]
plotting = ["matplotlib"]